import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Wallet from 'qp-walletprovider';
export default function Connect({ connect_wallet }) {
  const [haveMetamask, sethaveMetamask] = useState(true);
  const [address, setAddress] = useState([])


  const checkConnection = async () => {
    let wallet = new Wallet();
    wallet.getAccount().then((res) => {
      setAddress(res)
      connect_wallet(res[0].address);
    }).catch((e) => {
      console.log(e)
    })
  };

  const connectWeb3 = async () => {
    // try {
    //   const { ethereum } = window;

    //   if (!ethereum) {
    //     console.log("Metamask not detected");
    //     return;
    //   }

    //   const accounts = await ethereum.request({
    //     method: "eth_requestAccounts",
    //   });

    //   connect_wallet(accounts[0]);
    // } catch (error) {
    //   console.log("Error connecting to metamask", error);
    // }
    let wallet = new Wallet();
    wallet.connect().then((res) => {
      setAddress(res)
      connect_wallet(res[0].address);
    })
  };

  useEffect(() => {
    checkConnection();
  }, []);

  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
          type={"button"}
          name={"connect_wallet"}
          className={styles.btnConnect}
          onClick={connectWeb3}
        >
          Connect Wallet
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
